version: '3.8'

services:
  app:
    build: .
    image: bdren-student-analytics:${TAG:-latest}
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-student_analytics}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      - db
      - redis
    networks:
      - student_analytics_net

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-student_analytics}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - student_analytics_net

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - student_analytics_net

networks:
  student_analytics_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
