apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: bdren
type: Opaque
data:
  username: cHJvZF91c2Vy  # base64 encoded prod_user
  password: c2VjdXJlX3Bhc3N3b3Jk  # base64 encoded secure_password
  database: c3R1ZGVudF9hbmFseXRpY3NfcHJvZA==  # base64 encoded student_analytics_prod
  url: cG9zdGdyZXNxbDovL3Byb2RfdXNlcjpzZWN1cmVfcGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9zdHVkZW50X2FuYWx5dGljc19wcm9k  # base64 encoded connection URL
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: bdren
type: Opaque
data:
  url: cmVkaXM6Ly9yZWRpczozNjc5LzA=  # base64 encoded redis://redis:6379/0
