apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: bdren-production
type: Opaque
stringData:
  username: postgres
  password: CHANGE_ME_IN_PRODUCTION
  database: student_data_db
  url: postgresql://postgres:CHANGE_ME_IN_PRODUCTION@postgres:5432/student_data_db
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: bdren-production
type: Opaque
stringData:
  password: CHANGE_ME_IN_PRODUCTION
  url: redis://:CHANGE_ME_IN_PRODUCTION@redis:6379
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: bdren-production
type: Opaque
stringData:
  secret-key: CHANGE_ME_IN_PRODUCTION_SUPER_SECRET_KEY
  jwt-secret: CHANGE_ME_IN_PRODUCTION_JWT_SECRET
  encryption-key: CHANGE_ME_IN_PRODUCTION_ENCRYPTION_KEY
